// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NokoodAssignment.Persistence.DatabaseContext;

#nullable disable

namespace NokoodAssignment.Persistence.Migrations
{
    [DbContext(typeof(NokoodDBContext))]
    partial class NokoodDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NokoodAssignment.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("AppTB_Reservation", (string)null);
                });

            modelBuilder.Entity("NokoodAssignment.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AppTB_Trip", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4e0ddd4-044a-9b18-05f9-f2a77a42f779"),
                            CityName = "Sipeshaven",
                            Content = "cross-platform Saint Barthelemy Shores Auto Loan Account parsing Central sticky Infrastructure Borders open-source Developer Soft Health & Music service-desk Facilitator Optimization Unbranded Steel Chicken Senior Product interface Aruban Guilder Architect Garden throughput Djibouti Dynamic Metal Electronics Checking Account copy drive mobile Future Fresh panel Designer Liechtenstein Ergonomic Guarani Borders circuit Fresh Product green Intelligent Wooden Table Specialist AI Arizona Administrator Estates AI Books withdrawal eco-centric fault-tolerant User-friendly Egypt Fully-configurable connecting synthesize",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/abstract",
                            Name = "User-friendly",
                            Price = 150.41999999999999
                        },
                        new
                        {
                            Id = new Guid("8c9d37c2-7022-f934-ca4a-723501e8aa06"),
                            CityName = "Tyrafurt",
                            Content = "networks North Dakota benchmark envisioneer Hong Kong Frozen South Carolina Dynamic reintermediate morph Seychelles Rupee Small Cotton Chair Unbranded Practical Cotton Ball plum Generic Rubber Keyboard invoice Cape Verde unleash global Borders Monitored bottom-line Park Money Market Account payment violet focus group Nepalese Rupee pixel back up Money Market Account maximized mint green architectures Toys, Toys & Computers Fork Intelligent Beauty & Beauty Strategist override Generic Metal Ball visionary Malagasy Ariary object-oriented Small Granite Hat payment online Assimilated Practical Cotton Bike input strategize Courts Health Road deposit Center Principal Maryland Games, Automotive & Music",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/city",
                            Name = "Rustic Concrete Computer",
                            Price = 145.81999999999999
                        },
                        new
                        {
                            Id = new Guid("8e15a41d-fef3-2ef7-23b6-8fa565d0b17c"),
                            CityName = "New Marquesbury",
                            Content = "multi-byte Metrics communities sexy Granite Wooden transmitter transitional Ouguiya Fantastic Frozen Shirt Course Plains Rustic Fresh Table salmon Coordinator Plastic 1080p Bedfordshire reboot Health Berkshire Buckinghamshire Handmade Fresh Ball port Lead array Intelligent Wooden Chips Estate North Carolina brand Texas program Borders Licensed Wooden Bike Awesome Concrete Pants JBOD Silver SAS connecting JBOD Team-oriented Computers Groves Games PNG Assistant implementation Maine firmware open-source deposit EXE Division Pass 24/7 Samoa Well reboot Wooden Path",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/business",
                            Name = "embrace",
                            Price = 777.66999999999996
                        },
                        new
                        {
                            Id = new Guid("51f62381-5060-b3a0-4865-e13e77d5cd13"),
                            CityName = "Jazmyneberg",
                            Content = "Ports Extended orchestrate Greenland calculate override Kansas Springs lavender payment Concrete Handmade Wooden Computer Sleek Plastic Table Sleek leading-edge target primary withdrawal New Hampshire action-items Buckinghamshire non-volatile Officer Extensions web-readiness Eritrea viral Moldovan Leu Washington protocol Mauritius Rupee Officer markets Cambridgeshire North Korean Won Creative Handmade Concrete Shoes Implementation back-end Brunei Dollar Bond Markets Units European Composite Unit (EURCO) Cotton West Virginia mobile Australian Dollar Future Music & Garden frame redundant Throughway Plain California olive cyan Circle Nakfa array Home Loan Account convergence needs-based",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/business",
                            Name = "bi-directional",
                            Price = 482.52999999999997
                        },
                        new
                        {
                            Id = new Guid("4ca07784-db0e-1ecf-fdeb-c9e549deada1"),
                            CityName = "Greenfort",
                            Content = "generate Coordinator Gorgeous Cotton Ball Pass Home, Home & Automotive parse Arizona transmitting Borders multi-byte Western Sahara payment Sudan budgetary management Savings Account RAM transform Graphical User Interface solution-oriented Gorgeous Granite Fish Mexican Peso capacitor Concrete partnerships Refined Turkey violet Accounts synthesizing deposit mesh Tunisian Dinar Berkshire Switchable matrix Rustic Granite Chair open-source Savings Account bottom-line Gourde monitor Small California Usability Savings Account Solomon Islands Dollar Incredible Cotton Shirt Computers & Shoes Lek Chief background Connecticut communities applications Re-engineered transform orchid Mission Response Analyst",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/sports",
                            Name = "mobile",
                            Price = 796.70000000000005
                        },
                        new
                        {
                            Id = new Guid("d9a7744c-2878-531f-77cb-b893e558ffd3"),
                            CityName = "Brionnahaven",
                            Content = "Avon Clothing quantifying Surinam Dollar Malawi revolutionize reboot solution-oriented synthesizing didactic static mobile pixel asynchronous indigo open-source array empowering salmon contingency strategy invoice Handcrafted Granite Bike Optimization Leone Gorgeous Metal Bike Markets District Ouguiya Walk transmit evolve ROI virtual Global Representative backing up Frozen Decentralized Saint Helena Pound Wooden deposit digital cultivate homogeneous Group Sports, Books & Grocery virtual Graphic Interface 24/365 monitor 24/365 Bangladesh THX Track channels turquoise Awesome Frozen Gloves withdrawal reintermediate",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/business",
                            Name = "Cuban Peso Convertible",
                            Price = 968.92999999999995
                        },
                        new
                        {
                            Id = new Guid("199d9dee-5811-afdd-1f20-3e77d10807a0"),
                            CityName = "South Geofort",
                            Content = "systemic Liberian Dollar optical repurpose Money Market Account Games impactful Games magnetic Dale Bedfordshire Soft Tasty Metal Soap Handmade Frozen Ball index Shoes & Computers collaboration payment Engineer synthesize Moroccan Dirham Kansas Granite Rwanda Franc Customer database Lead Shoes invoice Auto Loan Account override Handmade Brand Missouri Consultant world-class Cloned USB Specialist firewall Avon Fiji Dollar bypassing cutting-edge Human integrate driver Cedi Rubber teal Sports & Music indexing Baby & Music Fork Ways Inverse New York Loop synthesizing Plaza",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/city",
                            Name = "Borders",
                            Price = 277.86000000000001
                        },
                        new
                        {
                            Id = new Guid("6bb2cc0d-51fa-f492-0eb6-55177a27af6e"),
                            CityName = "West Tobyhaven",
                            Content = "Fantastic Cotton Ball content withdrawal violet RAM orchid Jewelery, Games & Beauty Idaho Books & Baby Consultant Rustic Cotton Chips Groves Avon grey national FTP Licensed Cotton Computer quantify Vermont protocol leading edge transmit overriding monitor Credit Card Account parse Greece drive Rubber Path Overpass auxiliary Developer infrastructures Orchestrator Generic Fresh Chair granular integrated Turnpike Technician generate optical innovative Human black Steel engage primary Refined Wooden Pizza program Spring Personal Loan Account parse Ville extensible Small Cotton Pizza transmitter Dynamic e-commerce Electronics, Games & Grocery",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/nightlife",
                            Name = "Concrete",
                            Price = 925.95000000000005
                        },
                        new
                        {
                            Id = new Guid("bb017765-6a33-65bc-2026-667fcd3f91a1"),
                            CityName = "Pfannerstillfort",
                            Content = "Markets primary e-business FTP Ergonomic Plastic Towels Avon Product deploy end-to-end Legacy Specialist Bulgarian Lev real-time asymmetric Investor best-of-breed Cayman Islands Sudanese Pound Key Direct Investor Integration Handcrafted Granite Chicken online 1080p SMTP Tasty Metal Ball Streets compelling Common Dynamic Kwanza Lilangeni Awesome Fresh Bacon Minnesota Botswana USB ADP high-level Bridge program generate Practical Fresh Bike Cotton Togo Cambridgeshire quantifying Designer Borders Unions Field back up iterate Libyan Dinar Coordinator Forward ROI holistic Group payment",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/technics",
                            Name = "firewall",
                            Price = 237.00999999999999
                        },
                        new
                        {
                            Id = new Guid("2193acf1-74a4-c4d2-546d-76135d554fa3"),
                            CityName = "Kihnland",
                            Content = "invoice Bedfordshire Gorgeous Concrete Ball Connecticut pink responsive Synchronised Versatile Communications Strategist Implementation mobile zero administration local area network Cross-group local invoice Colorado UAE Dirham Incredible Plastic Gloves synergize models collaborative Hryvnia firewall instruction set Steel Directives syndicate Books & Grocery Technician application Granite Kids pixel web-readiness implementation leverage bluetooth enhance Games Moldovan Leu Investor array Mandatory open-source initiative Enhanced firmware Interactions primary Circles Yen Savings Account National Optimization Gateway Divide black infrastructure",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/people",
                            Name = "Human",
                            Price = 160.31
                        },
                        new
                        {
                            Id = new Guid("de7a1bf1-86b4-a5e4-42c6-c75bafa66c0b"),
                            CityName = "Kaleburgh",
                            Content = "Rubber Analyst Handmade neural capacitor matrix visualize Aruba Antarctica (the territory South of 60 deg S) Advanced CSS connect reinvent mint green Bedfordshire Configuration enhance mint green Cambridgeshire collaborative Legacy Expressway Avon e-business microchip efficient teal Delaware Forges interface Networked Creative Cambridgeshire needs-based seize program transmitting Generic Cotton Computer California Re-contextualized Awesome Baby & Kids District mission-critical intangible Intelligent 1080p regional HDD Causeway Assurance Soft Saint Vincent and the Grenadines Gardens Reduced payment Cayman Islands bandwidth application Crossroad",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/animals",
                            Name = "Garden, Home & Shoes",
                            Price = 580.94000000000005
                        },
                        new
                        {
                            Id = new Guid("dd9de15a-f3fa-eaa3-3f33-16887f457188"),
                            CityName = "Manteshire",
                            Content = "Small Cotton Pants Movies, Shoes & Health User-centric Gold Refined Dong Kina Agent Directives Rustic Soft Hat collaborative Gorgeous navigate Way Ranch Central Buckinghamshire Tasty Granite Soap Cambridgeshire 6th generation Music & Sports Cambridgeshire overriding superstructure RSS channels Island input Unbranded Rubber Keyboard transparent Customer-focused Point Rand Directives programming e-markets Ways grey Functionality convergence Pakistan Rupee web-enabled Road Bahamian Dollar violet Row Licensed Wooden United Arab Emirates infrastructure invoice orange grow Handmade Soft Fish Prairie redundant Liaison Practical Concrete Towels Sleek Soft Keyboard Handmade",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/business",
                            Name = "Enterprise-wide",
                            Price = 88.620000000000005
                        },
                        new
                        {
                            Id = new Guid("536672ae-e64d-030b-41a9-4da7c626a2e4"),
                            CityName = "Stromantown",
                            Content = "payment Interactions paradigms Kina Planner Borders Fresh Refined Fresh Towels Alabama program Integrated indexing Generic models Dynamic Investor coherent Canada next-generation payment Health & Jewelery deposit system engine CSS index Engineer drive Gardens cyan motivating installation PCI Buckinghamshire deposit Gorgeous Granite Mouse withdrawal Functionality Handmade Concrete Hat harness Integrated Accountability Music, Music & Jewelery Technician Turnpike GB Course Reactive Credit Card Account capacitor Operations Licensed Frozen Car back up killer Home Loan Account Sleek Coves payment Buckinghamshire deposit Jewelery, Electronics & Books",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/transport",
                            Name = "Future-proofed",
                            Price = 882.27999999999997
                        },
                        new
                        {
                            Id = new Guid("17a7b6ca-1e11-277d-e898-be5706bff707"),
                            CityName = "East Jarrod",
                            Content = "next-generation invoice Orchestrator Kroon Colorado systematic SCSI Money Market Account Administrator back up Forward Cambridgeshire Borders Branding Fresh Plastic analyzer Incredible Metal Pants withdrawal productize Jamaica copying hard drive green value-added firewall online Rubber Falkland Islands Pound firmware multi-byte Practical Granite Hat transmit engineer toolset contextually-based program Gold Poland Forge service-desk Awesome Plastic Chair e-business Buckinghamshire Bedfordshire circuit actuating array Denar Future Metal Investment Account Spurs Avon indexing Handcrafted Cotton Bike Reactive reboot green transmit",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/sports",
                            Name = "Cyprus",
                            Price = 514.57000000000005
                        },
                        new
                        {
                            Id = new Guid("a0b20f39-8a22-069f-7530-e2e6ad3f5681"),
                            CityName = "Demetrisfort",
                            Content = "Cliffs granular architectures Turks and Caicos Islands Licensed Granite Car New Mexico interface Investor Money Market Account firewall Mountains Branding SCSI hack Investor Investment Account Implementation seamless Borders Handmade sky blue withdrawal Ethiopia Bedfordshire Cotton RAM Home Loan Account program grey Tajikistan time-frame Outdoors & Toys collaborative optical Books, Shoes & Electronics Small iterate Squares seize Auto Loan Account generate Sao Tome and Principe generate Cotton Sports & Kids Licensed Fresh Bike copy Borders logistical Licensed Metal Sausages Ridge Re-engineered CSS Cotton facilitate Clothing & Music bandwidth Cambridgeshire sensor Latvian Lats",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ImageUrl = "http://lorempixel.com/640/480/nightlife",
                            Name = "Borders",
                            Price = 224.46000000000001
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NokoodAssignment.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("NokoodAssignment.Domain.Entities.Trip", null)
                        .WithMany("Reservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NokoodAssignment.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
